### PR TITLE
Refactor/remove nbsp checker

### PR DESCRIPTION
**Pull request by Bgeninatti**

### CODE REVIEW

**Comment by Bgeninatti** [comment]
Sorry. I'm making a spanish version of this and I created this by mistake here :)


BTW, Thanks for the awesome work!

**Comment by vpoulailleau** [comment]
Are you doing this for https://github.com/python/python-docs-es?

BTW, if you create some checkers that can be shared between the french version and the spanish version, any pull request will be appreciated.

Or maybe we can have a shared code with CLI flags?

**Comment by Seluj78** [comment]
Agreed ! I'm happy to see that what we've made is being used by others :grin: As Vincent said, I'd love it if we had a shared repo with multi language support ! Any PRs are welcome, even refactors !

**Comment by Bgeninatti** [comment]
Yes! I'm doing it for https://github.com/python/python-docs-es

I thought about the multi-language support and it would be great for other teams and future translations.

IMHO, despite the `GrammalecteChecker` all the checkers are useful or any language. Maybe is just about moving things to config files.
I'll open an issue to continue the discussion there!

Thanks and have a great weekend

**Pull request closed without merging**
